list = ["dog", "cat", "chicken"]
for animal in list:
    print(animal)
print(list)
print(len(list))
list.append("cow")
print(list)
print(len(list))
list.insert(2, "pig")
print(list)
print(len(list))
list.remove("cat")
print(list)
print(len(list))
list.pop()
print(list)
print(len(list))
list.reverse()
print(list)
print(len(list))
print(list[0])
print(len(list[0]))